contact_links:
    - name: Feature request
      url: https://github.com/WebArtWork/ngx-prime/issues
      about: Propose an enhancement by opening an issue.
    - name: Support
      url: https://github.com/WebArtWork/ngx-prime/issues
      about: Get help by opening an issue with a reproducible example.
